[package]
name = "kallistors"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
thiserror = "2.0.17"
croaring-sys = "4.4.1"
boomphf = "0.6.0"

[dev-dependencies]
tempfile = "3.24.0"
